### ISSUE TITLE
Header of News page does not respect translations

### ISSUE THREAD

**Issue by Sobeston** [ziglang/www.ziglang.org#104]
![image](https://user-images.githubusercontent.com/15335529/104748491-b7a1de80-5749-11eb-958a-b9155094070e.png)

**Comment by kristoff-it** [comment]
After thinking about this for a moment and retracing my line of thought, this is by design.
News items are not translated, so we want the section name (as it appears in the menu) to be translated,
but once you're in, then the content stays in English.  I think it would be more confusing if people saw the "News" title translated, but then the rest of the page wasn't.
