### ISSUE TITLE
I searched for array memory handling in the docs and didn't find it

### ISSUE THREAD

**Issue by lerno** [ziglang/www.ziglang.org#13]
The docs do not describe how arrays work with the rest of the memory handling, like how are they copied, how do you allocate them with an allocator, how do you copy a an array allocated with the stack allocator to use another allocator etc

**Comment by kristoff-it** [comment]
These are all reasonable questions that I believe cross the line between language reference and what a programming manual should teach. I believe it's better to keep the scope of the official docs contained and rely on community contributions, including actual books that people hopefully will write in the future, and of course existing ones that are not about Zig specifically, since most of those concepts are dependent on the machine architecture (+ OS APIs) rather than the language.

An existing example of this type of content being created by the community is https://ziglearn.org.
