### ISSUE TITLE
https://ziglang.org/news/ would be better as link out to https://zig.news/ ?

### ISSUE THREAD

**Issue by guidorice** [ziglang/www.ziglang.org#155]
The /news page on ziglang.org was only updated 2x in this calendar year... consider maybe replacing it with a link out to https://zig.news.

**Comment by AlekSi** [comment]
I think both updating https://ziglang.org/news/ or removing it would be better than keeping it outdated.

**Comment by kristoff-it** [comment]
ziglang.org/news is where we publish news from the zig software foundation.

zig.news is instead a social blogging platform for the community (see the [FAQ](https://zig.news/faq)). 

There is no connection between the two things. As for the fact that there are no recent post on the zsf new section, well, that's because there hasn't been any event that we deemed worthy of a news entry. We're busy working on the compiler at the moment, but I'm sure we'll eventually have something interesting enough to warrant a post there.
