### ISSUE TITLE
Is it possible to consider adding translations for the latest stable version of the documentation？

### ISSUE THREAD

**Issue by C-BJ** [ziglang/www.ziglang.org#186]

**Comment by AliChraghi** [comment]
which page do you mean?

**Comment by C-BJ** [comment]
> which page do you mean?

https://ziglang.org/documentation/0.9.0/ and https://ziglang.org/documentation/0.9.0/std/

Of course the versions can be different, but I don't think master needs to be translated

**Comment by C-BJ** [comment]
I do not understand why https://ziglang.org/documentation/0.9.0/ and https://ziglang.org/documentation/0.9.0/std/ have a different appearance

**Comment by AliChraghi** [comment]
currently i disagree with the translation of documention. because the concepts and words are very simple and the programmer is expected to know this words. there is also no guarantee that the people who wrote the translation of the previous pages will be willing to do so and this isn't possible due to the small community

**Comment by AliChraghi** [comment]
> I do not understand why https://ziglang.org/documentation/0.9.0/ and https://ziglang.org/documentation/0.9.0/std/ have a different appearance

@kristoff-it apparnace palate is bullshit 🙄. but consider that stdlib documentation is still wip

**Comment by C-BJ** [comment]
> currently i disagree with the translation of documention. because the concepts and words are very simple and the programmer is expected to know this words. there is also no guarantee that the people who wrote the translation of the previous pages will be willing to do so and this isn't possible due to the small community

The translation of the document is really big, but unlike the translation of the first few pages, the document can be partially localized and the rest remains in English.
I also agree with you that translation may not be necessary, but I think it's only a matter of time

**Comment by nektro** [comment]
there is no latest stable version

**Comment by C-BJ** [comment]
> there is no latest stable version

I mean the version with the version number, not the dev (master) version.

**Comment by nektro** [comment]
its the latest release, not the latest stable

**Comment by C-BJ** [comment]
> its the latest release, not the latest stable. i'll open an issue to have the copy fixed

It doesn't hurt that，I just want to say that the version to be translated should have a version number, not the development (main) version.

**Comment by C-BJ** [comment]
> its the latest release, not the latest stable. i'll open an issue to have the copy fixed

If version 1.0 comes, will the page have to be changed again?

**Comment by kristoff-it** [comment]
@C-BJ are you interested in contributing a translation for the language reference? Or are you asking more in general? 

The documentation for the standard library can't be translated because it's autogenerated and the current system that we use to autogenerate them is about to be scrapped in favor of a new one. Even then, these docs are based on the actual comments in the source code, translation seems hard do to, and easy to go out of sync.

The language reference changes less often and since it's hand-written, translating (and keeping track of changes), seems more feasible. That said, I honestly think that it might be better to wait and translate a better learning resource than the language reference. A better learning resource would be something like Zig Learn or a Zig book.
