### ISSUE TITLE
Chinese page layout problem

### ISSUE THREAD

**Issue by C-BJ** [ziglang/www.ziglang.org#207]
![image](https://user-images.githubusercontent.com/62678643/174464313-b3714dbd-44d8-4294-8e0a-367077a1058d.png)
It is obviously different from the English interface layout, but I can't find the reason
@kristoff-it

**Comment by p0d4r14n** [comment]
@C-BJ What exactly do you mean? The missing "lines" at the version number or that the "Latest Release" is not translated? Otherwise it seems fine to me.
If you mean the missing "lines" - that's because the container is too narrow. The lines will only show if the container is at least 156px wide. A min-width could be added to the container if it is considered as inconsistency or design flaw.

**Comment by C-BJ** [comment]
I mean the missing "lines", I don't know how to solve it
@p0d4r14n
